global:
  scrape_interval: 1s

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9091"]

  - job_name: "node"
    static_configs:
      - targets:
          - "192.168.1.2:9100"
          - "192.168.1.11:9100"
          - "192.168.1.13:9100"
          - "192.168.1.12:9100"
          - "192.168.1.15:9100"
          - "192.168.1.6:9100"

